// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";



export default defineConfig({
  schema: "schema.prisma",
  datasource: {
    //url: "postgresql://postgres.bvmnuoafwtjljqewvupd:[Peculiar@5571_jinx]]@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres",
    url: "postgresql://postgres.bvmnuoafwtjljqewvupd:3GSx9rcd9PEvBPry@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres"
  },

  migrations: {
    path: "migrations",
  },

});

